// Generated by https://pagedraw.io/pages/11385
import React from 'react';
import './dashboard.css';


function render() {
    return <div className="dashboard-dashboard-1">
        <div className="dashboard-0">
            <div className="dashboard-0-0">
                <div className="dashboard-0-0-0">
                    <div className="dashboard-customers-3">
                        <div className="dashboard-0-0-0-0-0">
                            <div className="dashboard-customers-5">Customers</div>
                            <div className="dashboard-0-0-0-0-0-1" /> 
                            <div className="dashboard-4">4125</div>
                        </div>
                        <div className="dashboard-0-0-0-0-1">
                            <div className="dashboard-current_year-1">
                                <div className="dashboard-0-0-0-0-1-0-0">
                                    <div className="dashboard-last_year-1" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="dashboard-0-0-1">
                    <div className="dashboard-activity-6">
                        <div className="dashboard-0-0-1-0-0">
                            <div className="dashboard-activity_weekly_avg-1">
                                {"Activity (weekly avg)"}
                            </div>
                            <div className="dashboard-0-0-1-0-0-1" /> 
                        </div>
                        <div className="dashboard-0-0-1-0-1">
                            <div className="dashboard-oval-4">
                                <div className="dashboard-0-0-1-0-1-0-0">
                                    <div className="dashboard-0-0-1-0-1-0-0-0">
                                        <div className="dashboard-group_3">
                                            <div className="dashboard-0-0-1-0-1-0-0-0-0-0">
                                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1736607398282130-1531926208712-88E76379-0B08-454B-A74C-F94041770687.png" className="dashboard-star-1" /> 
                                            </div>
                                        </div>
                                        <div className="dashboard-path_3" /> 
                                        <div className="dashboard-45">{"45%"}</div>
                                    </div>
                                </div>
                                <div className="dashboard-0-0-1-0-1-0-1" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="dashboard-0-1">
                <div className="dashboard-0-1-0">
                    <div className="dashboard-visits-4">
                        <div className="dashboard-0-1-0-0-0">
                            <div className="dashboard-visits_3">
                                {"visits (30 day avg)"}
                            </div>
                            <div className="dashboard-0-1-0-0-0-1" /> 
                            <div className="dashboard-1">{"12%"}</div>
                        </div>
                        <div className="dashboard-0-1-0-0-1" /> 
                        <div className="dashboard-0-1-0-0-2">
                            <div className="dashboard-3">3,920</div>
                            <div className="dashboard-4_">4,391</div>
                        </div>
                        <div className="dashboard-0-1-0-0-3">
                            <div className="dashboard-0-1-0-0-3-0" /> 
                            <div className="dashboard-2">2017</div>
                            <div className="dashboard-0-1-0-0-3-2" /> 
                            <div className="dashboard-20">2018</div>
                            <div className="dashboard-0-1-0-0-3-4" /> 
                        </div>
                    </div>
                </div>
                <div className="dashboard-0-1-1">
                    <div className="dashboard-conversion-3">
                        <div className="dashboard-0-1-1-0-0">
                            <div className="dashboard-0-1-1-0-0-0">
                                <div className="dashboard-0-1-1-0-0-0-0">
                                    <div className="dashboard-conversion-1">conversion</div>
                                </div>
                                <div className="dashboard-0-1-1-0-0-0-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9836827748235009-1531926208699-5E19DB3A-255B-4075-8EFC-35DA94074A86.png" className="dashboard-star-9" /> 
                                </div>
                            </div>
                            <div className="dashboard-0-1-1-0-0-1">
                                <div className="dashboard-0-1-1-0-0-1-0">
                                    <div className="dashboard-0-1-1-0-0-1-0-0">
                                        <div className="dashboard-oval-1">
                                            <div className="dashboard-0-1-1-0-0-1-0-0-0-0">
                                                <div className="dashboard-path_3-4" /> 
                                            </div>
                                        </div>
                                        <div className="dashboard-7">{"75%"}</div>
                                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1401643721400469-1531926208697-28B52130-CD6A-4A12-BC4F-EEBB29735A76.png" className="dashboard-star-14" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="dashboard-0-1-1-0-1" /> 
                    </div>
                </div>
                <div className="dashboard-0-1-2">
                    <div className="dashboard-test_coverage-15">
                        <div className="dashboard-0-1-2-0-0">
                            <div className="dashboard-0-1-2-0-0-0">
                                <div className="dashboard-0-1-2-0-0-0-0">
                                    <div className="dashboard-test_coverage-1">
                                        Test coverage
                                    </div>
                                </div>
                                <div className="dashboard-0-1-2-0-0-0-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2830350432310295-1531926208687-3F41D218-A3BE-402D-A9C2-2D140CFF3327.png" className="dashboard-star-2" /> 
                                </div>
                            </div>
                            <div className="dashboard-0-1-2-0-0-1">
                                <div className="dashboard-0-1-2-0-0-1-0">
                                    <div className="dashboard-0-1-2-0-0-1-0-0">
                                        <div className="dashboard-oval-2">
                                            <div className="dashboard-0-1-2-0-0-1-0-0-0-0">
                                                <div className="dashboard-path_3-8" /> 
                                            </div>
                                        </div>
                                        <div className="dashboard-49">{"49%"}</div>
                                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/3082272320192316-1531926208685-B7555F6B-4539-46B0-BD6D-E087479A0033.png" className="dashboard-star-3" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="dashboard-0-1-2-0-1" /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
